### ISSUE TITLE
Cancel Recording on iOS app?

### ISSUE THREAD

**Issue by TerryLansdown** [zipleen/tvheadend-ios-lib#10]
Hi, thanks for the app, very nice.

How can you cancel a recording that has started from the app? I can't see any way to do this.

**Comment by zipleen** [comment]
In the recordings tab, in the first tab upcoming, if a recording is currently under way you can see it there. You can go into it and hit stop. This should cancel the recording and tvheadend will move it to the failed tab

**Comment by TerryLansdown** [comment]
Great, for that, current recordings weren’t showing up, but seems fine now. 

Thanks, t
