### ISSUE TITLE
tvOS 11.2 supports matching frame rates

### ISSUE THREAD

**Issue by tunip** [zipleen/tvheadend-ios-lib#8]
https://developer.apple.com/videos/play/fall2017/503/

Would we see this in the TvhClient app for Apple TV 4K?

Thx

**Comment by zipleen** [comment]
Join chat.tvhclient.com and you’ll see we’ve already discussed this :p

Vlckit just support this to be done correctly, as soon as it does I will push it

**Comment by tunip** [comment]
Thx for the quick answer. Found also the feature request in vlckit GitLab:
https://code.videolan.org/videolan/VLCKit/issues/119
